package com.sixbank.accountlibrary.utility;

import java.security.SecureRandom;

/**
 * Utility class for generating and managing account numbers for customer or internal accounts.
 * <p>
 * Account numbers follow the format: {@code SIXxxxxxxxxxx}, where:
 * <ul>
 *   <li>{@code SIX} is a fixed system prefix</li>
 *   <li>{@code xxxxxxxxxx} is a 10-character uppercase alphanumeric string</li>
 * </ul>
 * Example: {@code SIXD29KF83LQ}
 *
 * <p>
 * Features:
 * <ul>
 *   <li>Secure random generation using {@link SecureRandom}</li>
 *   <li>Simple validation of account number format</li>
 *   <li>Support for masking account numbers in logs or UIs</li>
 * </ul>
 *
 * <p><b>Usage Example:</b></p>
 * <pre>{@code
 * // Generate a new account number
 * String accountNumber = AccountNumberGenerator.generateAccountNumber();
 *
 * // Mask the account number for display
 * String masked = AccountNumberGenerator.maskAccountNumber(accountNumber);
 * }</pre>
 *
 * @author SixBank
 * @since 0.0.1
 */
public final class AccountNumberGenerator {

    private static final String PREFIX = "SIX";
    private static final int RANDOM_LENGTH = 10;
    private static final String CHAR_POOL = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    private static final SecureRandom RANDOM = new SecureRandom();

    private AccountNumberGenerator() {
        // Prevent instantiation
    }

    /**
     * Generates a new account number with the format: {@code SIXxxxxxxxxxx}
     *
     * @return a newly generated account number, e.g., {@code SIX9G7L2B5Q1W}
     */
    public static String generateAccountNumber() {
        StringBuilder sb = new StringBuilder(PREFIX);
        for (int i = 0; i < RANDOM_LENGTH; i++) {
            int index = RANDOM.nextInt(CHAR_POOL.length());
            sb.append(CHAR_POOL.charAt(index));
        }
        return sb.toString();
    }

    /**
     * Returns a masked version of the given account number, showing only the last 4 characters.
     * Example: {@code SIX******Q1W}
     *
     * @param accountNumber the full account number
     * @return masked account number, or original input if format is invalid or too short
     */
    public static String maskAccountNumber(String accountNumber) {
        if (accountNumber == null || accountNumber.length() < 6) {
            return accountNumber; // Return as-is if too short to mask
        }

        int unmaskedLength = 4;
        int maskLength = accountNumber.length() - unmaskedLength;

        String maskedPart = "*".repeat(maskLength);
        String unmaskedPart = accountNumber.substring(maskLength);

        return maskedPart + unmaskedPart;
    }

    /**
     * Validates if a given string is a valid account number generated by this utility.
     *
     * @param accountNumber the account number to validate
     * @return true if valid, false otherwise
     */
    public static boolean isValidAccountNumber(String accountNumber) {
        if (accountNumber == null || accountNumber.length() != PREFIX.length() + RANDOM_LENGTH) {
            return false;
        }
        return accountNumber.startsWith(PREFIX)
                && accountNumber.substring(PREFIX.length()).matches("^[A-Z0-9]{" + RANDOM_LENGTH + "}$");
    }
}

